# Generated by Django 3.1.6 on 2021-02-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchparameters',
            name='genre',
        ),
        migrations.AddField(
            model_name='searchparameters',
            name='genre_id',
            field=models.CharField(default='0', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchparameters',
            name='platform',
            field=models.CharField(max_length=15),
        ),
    ]
