# Generated by Django 3.1.6 on 2021-02-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210215_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchparameters',
            name='platform',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
